### ISSUE TITLE
Current state / release?

### ISSUE THREAD

**Issue by MoritzMaxeiner** [antoyo/gdbus-rs#1]
Hello, I was wondering in what state this currently is in (alpha, beta, worksforme, etc.) and if you would be willing to release it and add it to https://crates.io/ ?

**Comment by antoyo** [comment]
This crate is in very early stage: I don't recommand you to use it because there are bugs and calls can sometimes timeout.
Moreover, I had to do a workaround because of [this issue](https://github.com/gtk-rs/gir/issues/288) so I cannot upload it to crates.io.
I think this crate needs to be rewritten with another design (or wait to see how the Rust and GNOME communities will do it).
Thanks for your interest.

**Comment by MoritzMaxeiner** [comment]
Okay, thank you for the explanation, guess I'll have to go with the low-level gio-sys API, then. 
FYI: Regarding another design: I tried using the [gio gir](https://raw.githubusercontent.com/gtk-rs/gir-files/71d73f05707e0f4800274c6440a0d493fbe71646/Gio-2.0.gir) file to see whether auto generation with the [gir codegen tool](https://github.com/gtk-rs/gir) would work (like it does for gudev), but so far it seems to me that the high level APIs described for gdbus in there aren't complete (I see no high level mapping for e.g. acquiring a bus name).
